/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attendance */
        get: operations["list_attendance_api_v1_attendance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/unattributed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unattributed
         * @description F4: read-only reconciliation diagnostics.
         *
         *     Unattributed attendance rows with per-row resolver reasoning (NO_DEVICE_USER /
         *     LEGACY_USER / NO_MAPPING / BEFORE_VALID_FROM / INSIDE_INTERVAL / AFTER_VALID_TO).
         *     Never writes — attribution stays with the canonical VERIFIED temporal mapping.
         */
        get: operations["unattributed_api_v1_attendance_unattributed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/{attendance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attendance */
        get: operations["get_attendance_api_v1_attendance__attendance_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/{attendance_id}/raw-payload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attendance Raw Payload
         * @description Explicit diagnostics endpoint for raw attendance payload.
         */
        get: operations["get_attendance_raw_payload_api_v1_attendance__attendance_id__raw_payload_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Types */
        get: operations["event_types_api_v1_audit_event_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Operator changes their own password; all OTHER sessions are revoked.
         *
         *     The presenting token stays valid (its hash differs from the revoked set
         *     only if it belongs to this operator — we revoke tokens of this operator
         *     except the presented one). Logged as AUTH_PASSWORD_CHANGE.
         */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Summary */
        get: operations["dashboard_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Device Users */
        get: operations["list_device_users_api_v1_device_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device-users/{device_user_pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device User */
        get: operations["get_device_user_api_v1_device_users__device_user_pk__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_api_v1_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Enrollments */
        get: operations["list_enrollments_api_v1_enrollments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve */
        post: operations["reserve_api_v1_enrollments_reserve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enrollment Detail */
        get: operations["get_enrollment_detail_api_v1_enrollments__enrollment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_enrollments__enrollment_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}/confirm-controlled-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Scan */
        post: operations["confirm_scan_api_v1_enrollments__enrollment_id__confirm_controlled_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}/confirm-fingerprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Fingerprint */
        post: operations["confirm_fingerprint_api_v1_enrollments__enrollment_id__confirm_fingerprint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}/create-terminal-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Terminal Account */
        post: operations["create_terminal_account_api_v1_enrollments__enrollment_id__create_terminal_account_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}/mark-ready-for-mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Ready */
        post: operations["mark_ready_api_v1_enrollments__enrollment_id__mark_ready_for_mapping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}/next-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Next Actions
         * @description Returns the valid next operator actions for an enrollment's current state.
         *
         *     Computed from the canonical state machine (app.enrollment.ALLOWED_TRANSITIONS
         *     + ENROLLMENT_ACTIONS) so the frontend never duplicates workflow logic.
         *     Read-only — no state mutation. Physical terminal steps (e.g. terminal
         *     account creation) are intentionally absent: they happen at the terminal.
         */
        get: operations["get_next_actions_api_v1_enrollments__enrollment_id__next_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}/start-controlled-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Scan Window */
        post: operations["start_scan_window_api_v1_enrollments__enrollment_id__start_controlled_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}/start-fingerprint-enrollment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Fingerprint */
        post: operations["start_fingerprint_api_v1_enrollments__enrollment_id__start_fingerprint_enrollment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/humans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Humans */
        get: operations["list_humans_api_v1_humans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/humans/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Human */
        get: operations["get_human_api_v1_humans__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Human English Name */
        patch: operations["update_human_english_name_api_v1_humans__employee_id__patch"];
        trace?: never;
    };
    "/api/v1/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mappings */
        get: operations["list_mappings_api_v1_mappings_get"];
        put?: never;
        /** Create Mapping */
        post: operations["create_mapping_api_v1_mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mappings/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mapping Eligibility
         * @description READY_FOR_MAPPING enrollments with controlled-scan evidence.
         *
         *     F4: feeds the ADMIN mapping-creation form (POST /api/v1/mappings).
         *     Read-only; only enrollments whose device user has no overlapping VERIFIED
         *     mapping are offered, so a duplicate mapping can never be proposed.
         *     Registered before /{mapping_id} so FastAPI does not shadow it.
         */
        get: operations["mapping_eligibility_api_v1_mappings_eligibility_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mappings/{mapping_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mapping */
        get: operations["get_mapping_api_v1_mappings__mapping_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Operators */
        get: operations["list_operators_api_v1_operators_get"];
        put?: never;
        /** Create Operator */
        post: operations["create_operator_api_v1_operators_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operators/{operator_id}/toggle-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Active */
        post: operations["toggle_active_api_v1_operators__operator_id__toggle_active_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/ranks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ranks */
        get: operations["list_ranks_api_v1_reference_ranks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Realtime attendance events (SSE)
         * @description Server-Sent Events stream of attendance scans as published by the Collector on MQTT. Live-only (no replay). Requires a valid Bearer token (VIEWER+).
         */
        get: operations["stream_attendance_api_v1_stream_attendance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/write-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_v1_write_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/write-session/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Session */
        post: operations["close_session_api_v1_write_session_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/write-session/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Session */
        post: operations["open_session_api_v1_write_session_open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Attendance */
        Attendance: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Id */
            device_id?: number | null;
            /** Device Ip */
            device_ip: string;
            /** Device User Pk */
            device_user_pk?: number | null;
            /** Employee Id */
            employee_id?: string | null;
            /** Id */
            id: number;
            /** Punch Type */
            punch_type?: string | null;
            /**
             * Scan Time
             * Format: date-time
             */
            scan_time: string;
            /** Status */
            status: string;
            /** User Id */
            user_id: string;
        };
        /** AttendanceDetail */
        AttendanceDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Id */
            device_id?: number | null;
            /** Device Ip */
            device_ip: string;
            /** Device Name */
            device_name?: string | null;
            /** Device User Id */
            device_user_id?: string | null;
            /** Device User Pk */
            device_user_pk?: number | null;
            /** Employee Id */
            employee_id?: string | null;
            /** Employee Name */
            employee_name?: string | null;
            /** Id */
            id: number;
            /** Punch Type */
            punch_type?: string | null;
            /**
             * Scan Time
             * Format: date-time
             */
            scan_time: string;
            /** Status */
            status: string;
            /** User Id */
            user_id: string;
        };
        /** AttendanceRawPayload */
        AttendanceRawPayload: {
            /** Id */
            id: number;
            /** Raw Payload */
            raw_payload: {
                [key: string]: unknown;
            };
        };
        /** AttributionReasoning */
        AttributionReasoning: {
            /** Classification */
            classification: string;
            /** Detail */
            detail: string;
            /** Resolver Employee Id */
            resolver_employee_id?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** AuditEvent */
        AuditEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Ip */
            device_ip?: string | null;
            /** Event Type */
            event_type: string;
            /** Id */
            id: number;
            /** Message */
            message?: string | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ChangePasswordResponse */
        ChangePasswordResponse: {
            /** Changed */
            changed: boolean;
            /** Other Tokens Revoked */
            other_tokens_revoked: number;
        };
        /** CollectorSummary */
        CollectorSummary: {
            /** Db Status */
            db_status?: string | null;
            /** Device Connected */
            device_connected?: boolean | null;
            /** Loop Alive */
            loop_alive?: boolean | null;
            /** Mqtt Status */
            mqtt_status?: string | null;
            /** State */
            state?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * CreateMappingRequest
         * @description ADMS-FullEnrollment-E2E-Closure-017: employee_id, device_user_pk, and
         *     controlled_attendance_id are all derived server-side from the
         *     enrollment row (see app.mapping.create_verified_mapping) — the ADMIN
         *     confirming Step 6 supplies only which enrollment and why. This is a
         *     breaking API change (previously required 4 caller-supplied identity
         *     fields); every caller in this repository (Mappings.tsx, tests) is
         *     updated in the same change. It permanently closes the "frontend
         *     reconstructs security-critical mapping evidence from stale/nullable
         *     data" bug class that produced 422s at Step 6.
         */
        CreateMappingRequest: {
            /**
             * Enrollment Id
             * @description READY_FOR_MAPPING enrollment id
             */
            enrollment_id: number;
            /**
             * Verification Note
             * @description audit note referencing pilot evidence
             */
            verification_note: string;
            /**
             * Verified By
             * @description explicit operator/owner identity
             */
            verified_by: string;
        };
        /** CreateMappingResponse */
        CreateMappingResponse: {
            /** Device User Pk */
            device_user_pk: number;
            /** Employee Id */
            employee_id: string;
            /** Mapping Id */
            mapping_id: number;
            /** Mapping Status */
            mapping_status: string;
            /** Valid From */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Verification Method */
            verification_method: string;
            /** Verified At */
            verified_at: string;
        };
        /** CreateOperatorRequest */
        CreateOperatorRequest: {
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default VIEWER
             */
            role: string;
            /** Username */
            username: string;
        };
        /** CreateTerminalAccountRequest */
        CreateTerminalAccountRequest: {
            /**
             * Display Name
             * @description ASCII terminal display name
             */
            display_name: string;
            /**
             * Operator
             * @description explicit operator identity
             */
            operator: string;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Attendance Today */
            attendance_today: number;
            /** Attendance Total */
            attendance_total: number;
            /** Attendance Unattributed */
            attendance_unattributed: number;
            collector?: components["schemas"]["CollectorSummary"] | null;
            /** Device Users Active */
            device_users_active: number;
            /** Device Users Total */
            device_users_total: number;
            /** Device Users Unmapped */
            device_users_unmapped: number;
            /** Devices Active */
            devices_active: number;
            /** Devices Total */
            devices_total: number;
            /** Enrollments By Status */
            enrollments_by_status: {
                [key: string]: number;
            };
            /** Humans Excluded */
            humans_excluded: number;
            /** Humans Production Eligible */
            humans_production_eligible: number;
            /** Humans Total */
            humans_total: number;
            /** Mappings Total */
            mappings_total: number;
            /** Mappings Verified Active */
            mappings_verified_active: number;
        };
        /** Device */
        Device: {
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Id */
            device_id: number;
            /** Device Ip */
            device_ip: string;
            /** Device Name */
            device_name: string;
            /** Firmware Version */
            firmware_version?: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Platform */
            platform: string;
            /** Serial Number */
            serial_number: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DeviceUser */
        DeviceUser: {
            /**
             * Account Incarnation
             * @default 1
             */
            account_incarnation: number;
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Display Name */
            device_display_name?: string | null;
            /** Device Id */
            device_id: number;
            /** Device Uid */
            device_uid?: number | null;
            /** Device User Id */
            device_user_id: string;
            /** Device User Pk */
            device_user_pk: number;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Inactive At */
            inactive_at?: string | null;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Privilege */
            privilege: number;
            /** Roster Last Seen At */
            roster_last_seen_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Enrollment */
        Enrollment: {
            /** Confirmed At */
            confirmed_at?: string | null;
            /** Confirmed By */
            confirmed_by?: string | null;
            /** Controlled Scan Time */
            controlled_scan_time?: string | null;
            /** Controlled Scan Window Until */
            controlled_scan_window_until?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Id */
            device_id: number;
            /** Device Name */
            device_name?: string | null;
            /** Device Uid */
            device_uid?: number | null;
            /** Employee Id */
            employee_id: string;
            /** Employee Name */
            employee_name?: string | null;
            /**
             * English Name
             * @description Canonical terminal-safe (ASCII) name, when set on the Human Master record.
             */
            english_name?: string | null;
            /** Enrollment Id */
            enrollment_id: number;
            /** Fingerprint Confirmed At */
            fingerprint_confirmed_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Rank */
            rank?: string | null;
            /** @description Canonical RTN rank metadata (ADMS-OperatorUX-Fingerprint-Rank-Mapping-016) — presentation only, used to build the terminal display-name preview (rank_en_abbreviation + english_name). Never an identity authority. */
            rank_metadata?: components["schemas"]["RankMetadata"] | null;
            /**
             * Reserved At
             * Format: date-time
             */
            reserved_at: string;
            /** Reserved By */
            reserved_by: string;
            /** Reserved Device User Id */
            reserved_device_user_id: string;
            /** Status */
            status: string;
            /** Terminal Created At */
            terminal_created_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EnrollmentNextActions
         * @description Valid next operator actions for an enrollment's current state.
         */
        EnrollmentNextActions: {
            /** Enrollment Id */
            enrollment_id: number;
            /** Next Actions */
            next_actions: {
                [key: string]: string;
            }[];
            /** Status */
            status: string;
        };
        /**
         * EnrollmentReserveResult
         * @description Return of POST /api/v1/enrollments/reserve.
         */
        EnrollmentReserveResult: {
            /** Device Id */
            device_id: number;
            /** Employee Id */
            employee_id: string;
            /** Enrollment Id */
            enrollment_id: number;
            /**
             * Reserved At
             * Format: date-time
             */
            reserved_at: string;
            /** Reserved Device User Id */
            reserved_device_user_id: string;
            /** Status */
            status: string;
        };
        /**
         * EnrollmentTransitionResult
         * @description Return of enrollment transition POSTs.
         */
        EnrollmentTransitionResult: {
            /**
             * Controlled Scan Time
             * @description confirm-controlled-scan only: the REAL bound attendance scan_time (ADMS-ControlledScan-EvidenceBinding-018 — server-resolved, never an operator estimate). Null for every other transition.
             */
            controlled_scan_time?: string | null;
            /** Enrollment Id */
            enrollment_id: number;
            /**
             * Reconciled
             * @description create-terminal-account only: true if the terminal account already existed and this call reconciled ADMS state without a new set_user() call; false if this call performed the mutation; null for every other transition.
             */
            reconciled?: boolean | null;
            /** Status */
            status: string;
        };
        /**
         * EventTypesResponse
         * @description Return of GET /api/v1/audit/event-types.
         */
        EventTypesResponse: {
            /** Event Types */
            event_types: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            collector?: components["schemas"]["CollectorSummary"] | null;
            /** Database */
            database: string;
            /** Mqtt */
            mqtt?: string | null;
            /** Status */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** Healthz */
        Healthz: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** Human */
        Human: {
            /** Active */
            active: boolean;
            /** Branch */
            branch?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Employee Id */
            employee_id: string;
            /** English Name */
            english_name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Personnel Id */
            personnel_id?: string | null;
            /** Position */
            position?: string | null;
            /** Production Scope */
            production_scope: boolean;
            /** Rank */
            rank?: string | null;
            rank_metadata?: components["schemas"]["RankMetadata"] | null;
            /** Source */
            source: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Display Name */
            display_name: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Operator Id */
            operator_id: number;
            /** Role */
            role: string;
            /** Token */
            token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Username */
            username: string;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /** Revoked */
            revoked: boolean;
        };
        /** Mapping */
        Mapping: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device User Id */
            device_user_id?: string | null;
            /** Device User Pk */
            device_user_pk: number;
            /** Employee Id */
            employee_id: string;
            /** Employee Name */
            employee_name?: string | null;
            /** Mapping Id */
            mapping_id: number;
            /** Mapping Source */
            mapping_source: string;
            /** Mapping Status */
            mapping_status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Verification Method */
            verification_method?: string | null;
            /** Verification Note */
            verification_note?: string | null;
            /** Verified At */
            verified_at?: string | null;
            /** Verified By */
            verified_by?: string | null;
        };
        /** MappingEligibility */
        MappingEligibility: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["MappingEligibilityItem"][];
        };
        /** MappingEligibilityItem */
        MappingEligibilityItem: {
            /** Confirmed At */
            confirmed_at?: string | null;
            /** Confirmed By */
            confirmed_by?: string | null;
            /** Controlled Attendance Id */
            controlled_attendance_id?: number | null;
            /** Controlled Scan Time */
            controlled_scan_time?: string | null;
            /** Device Id */
            device_id: number;
            /** Device Name */
            device_name?: string | null;
            /** Device User Active */
            device_user_active?: boolean | null;
            /** Device User Id */
            device_user_id?: string | null;
            /** Device User Pk */
            device_user_pk?: number | null;
            /** Employee Id */
            employee_id: string;
            /** Employee Name */
            employee_name?: string | null;
            /** Enrollment Id */
            enrollment_id: number;
            /** Notes */
            notes?: string | null;
            /** Reserved Device User Id */
            reserved_device_user_id: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Display Name */
            display_name: string;
            /** Operator Id */
            operator_id: number;
            /** Role */
            role: string;
            /** Username */
            username: string;
            /**
             * Write Enabled
             * @default false
             */
            write_enabled: boolean;
            write_session?: components["schemas"]["WriteSessionStatus"] | null;
        };
        /** OpenWriteSessionRequest */
        OpenWriteSessionRequest: {
            /**
             * Reason
             * @description Why writes are being opened, e.g. 'Enrollment session — Bldg 3'
             */
            reason: string;
        };
        /** OperatorOut */
        OperatorOut: {
            /** Active */
            active: boolean;
            /** Created At */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Operator Id */
            operator_id: number;
            /** Role */
            role: string;
            /** Updated At */
            updated_at: string;
            /** Username */
            username: string;
        };
        /** Page[Attendance] */
        Page_Attendance_: {
            /** Items */
            items: components["schemas"]["Attendance"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[AuditEvent] */
        Page_AuditEvent_: {
            /** Items */
            items: components["schemas"]["AuditEvent"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[DeviceUser] */
        Page_DeviceUser_: {
            /** Items */
            items: components["schemas"]["DeviceUser"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[Device] */
        Page_Device_: {
            /** Items */
            items: components["schemas"]["Device"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[Enrollment] */
        Page_Enrollment_: {
            /** Items */
            items: components["schemas"]["Enrollment"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[Human] */
        Page_Human_: {
            /** Items */
            items: components["schemas"]["Human"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[Mapping] */
        Page_Mapping_: {
            /** Items */
            items: components["schemas"]["Mapping"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[UnattributedAttendance] */
        Page_UnattributedAttendance_: {
            /** Items */
            items: components["schemas"]["UnattributedAttendance"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** RankMetadata */
        RankMetadata: {
            /** Acting */
            acting?: string | null;
            /** Rank Category */
            rank_category?: string | null;
            /** Rank En */
            rank_en?: string | null;
            /** Rank En Abbreviation */
            rank_en_abbreviation?: string | null;
            /** Rank Th Abbreviation */
            rank_th_abbreviation?: string | null;
            /** Rank Th Full */
            rank_th_full?: string | null;
            /** Rank Th Original */
            rank_th_original: string;
        };
        /** RankReference */
        RankReference: {
            /** Rank Category */
            rank_category: string;
            /** Rank En */
            rank_en: string;
            /** Rank En Abbreviation */
            rank_en_abbreviation: string;
            /** Rank Th Abbreviation */
            rank_th_abbreviation: string;
            /** Rank Th Full */
            rank_th_full: string;
            /** Source */
            source: string;
        };
        /** ReserveRequest */
        ReserveRequest: {
            /**
             * Device Id
             * @description devices.device_id
             */
            device_id: number;
            /**
             * Employee Id
             * @description Human UUID
             */
            employee_id: string;
            /**
             * Operator
             * @description explicit operator identity
             */
            operator: string;
            /**
             * Roster User Ids
             * @description optional live terminal roster IDs (read-only evidence)
             */
            roster_user_ids?: unknown[] | null;
        };
        /**
         * ScanConfirmationRequest
         * @description ADMS-ControlledScan-EvidenceBinding-018: no scan_time field — the
         *     server resolves and binds the actual attendance evidence itself (see
         *     app.enrollment.confirm_controlled_scan). The operator/browser never
         *     supplies or estimates a scan time.
         */
        ScanConfirmationRequest: {
            /**
             * Operator
             * @description explicit operator identity
             */
            operator: string;
        };
        /** ToggleActiveRequest */
        ToggleActiveRequest: {
            /** Active */
            active: boolean;
        };
        /** ToggleActiveResponse */
        ToggleActiveResponse: {
            /** Active */
            active: boolean;
            /** Operator Id */
            operator_id: number;
            /** Username */
            username: string;
        };
        /** TransitionRequest */
        TransitionRequest: {
            /** Notes */
            notes?: string | null;
            /**
             * Operator
             * @description explicit operator identity
             */
            operator: string;
        };
        /** UnattributedAttendance */
        UnattributedAttendance: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Id */
            device_id?: number | null;
            /** Device Ip */
            device_ip: string;
            /** Device User Pk */
            device_user_pk?: number | null;
            /** Employee Id */
            employee_id?: string | null;
            /** Id */
            id: number;
            /** Punch Type */
            punch_type?: string | null;
            reasoning: components["schemas"]["AttributionReasoning"];
            /**
             * Scan Time
             * Format: date-time
             */
            scan_time: string;
            /** Status */
            status: string;
            /** User Id */
            user_id: string;
        };
        /** UpdateHumanEnglishNameRequest */
        UpdateHumanEnglishNameRequest: {
            /**
             * English Name
             * @description Full English name with Latin letters, spaces, hyphens, and apostrophes
             */
            english_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WriteSessionStatus
         * @description GET/open/close all return this shape. When active is False, every
         *     other field is absent.
         */
        WriteSessionStatus: {
            /** Active */
            active: boolean;
            /** Closed At */
            closed_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Opened At */
            opened_at?: string | null;
            /** Opened By */
            opened_by?: number | null;
            /** Opened By Name */
            opened_by_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Session Id */
            session_id?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_attendance_api_v1_attendance_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                employee_id?: string | null;
                device_user_pk?: number | null;
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Attendance_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unattributed_api_v1_attendance_unattributed_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UnattributedAttendance_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attendance_api_v1_attendance__attendance_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attendance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attendance_raw_payload_api_v1_attendance__attendance_id__raw_payload_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attendance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRawPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_types_api_v1_audit_event_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypesResponse"];
                };
            };
        };
    };
    list_events_api_v1_audit_events_get: {
        parameters: {
            query?: {
                event_type?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditEvent_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    dashboard_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    list_device_users_api_v1_device_users_get: {
        parameters: {
            query?: {
                device_id?: number | null;
                active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DeviceUser_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_user_api_v1_device_users__device_user_pk__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_user_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Device_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_v1_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_enrollments_api_v1_enrollments_get: {
        parameters: {
            query?: {
                status?: string | null;
                employee_id?: string | null;
                device_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Enrollment_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reserve_api_v1_enrollments_reserve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentReserveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enrollment_detail_api_v1_enrollments__enrollment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrollment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_enrollments__enrollment_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTransitionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_scan_api_v1_enrollments__enrollment_id__confirm_controlled_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTransitionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_fingerprint_api_v1_enrollments__enrollment_id__confirm_fingerprint_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTransitionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_terminal_account_api_v1_enrollments__enrollment_id__create_terminal_account_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTerminalAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTransitionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_ready_api_v1_enrollments__enrollment_id__mark_ready_for_mapping_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTransitionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_next_actions_api_v1_enrollments__enrollment_id__next_actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentNextActions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_scan_window_api_v1_enrollments__enrollment_id__start_controlled_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTransitionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_fingerprint_api_v1_enrollments__enrollment_id__start_fingerprint_enrollment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTransitionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
    list_humans_api_v1_humans_get: {
        parameters: {
            query?: {
                production_scope?: boolean | null;
                search?: string | null;
                category?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Human_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_human_api_v1_humans__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Human"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_human_english_name_api_v1_humans__employee_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHumanEnglishNameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Human"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mappings_api_v1_mappings_get: {
        parameters: {
            query?: {
                employee_id?: string | null;
                device_user_pk?: number | null;
                mapping_status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Mapping_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mapping_api_v1_mappings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMappingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMappingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mapping_eligibility_api_v1_mappings_eligibility_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingEligibility"];
                };
            };
        };
    };
    get_mapping_api_v1_mappings__mapping_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_operators_api_v1_operators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorOut"][];
                };
            };
        };
    };
    create_operator_api_v1_operators_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOperatorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_active_api_v1_operators__operator_id__toggle_active_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleActiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleActiveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ranks_api_v1_reference_ranks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankReference"][];
                };
            };
        };
    };
    stream_attendance_api_v1_stream_attendance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_status_api_v1_write_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteSessionStatus"];
                };
            };
        };
    };
    close_session_api_v1_write_session_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteSessionStatus"];
                };
            };
        };
    };
    open_session_api_v1_write_session_open_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenWriteSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteSessionStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
        };
    };
}
