FROM python:3.12-slim

WORKDIR /app
COPY app/requirements.txt ./requirements.txt
COPY app/requirements-api.txt ./requirements-api.txt
RUN pip install --no-cache-dir -r requirements.txt -r requirements-api.txt
COPY app/ ./app/

EXPOSE 8081
CMD ["python", "-m", "app.api"]
